Fix 'elided lifetimes' warning
```
error: hidden lifetime parameters in types are deprecated
  --> library/stdarch/crates/std_detect/src/detect/os/linux/cpuinfo.rs:20:48
   |
20 |     pub(crate) fn field(&self, field: &str) -> CpuInfoField {
   |                                                ^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
   |
   = note: `-D elided-lifetimes-in-paths` implied by `-D warnings`
```

This lint is allow by default, which is why this wasn't spotted earlier.